set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
 
set_property PACKAGE_PIN U16 [get_ports {rd1[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd1[0]}]
set_property PACKAGE_PIN E19 [get_ports {rd1[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd1[1]}]
set_property PACKAGE_PIN U19 [get_ports {rd1[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd1[2]}]
set_property PACKAGE_PIN V19 [get_ports {rd1[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd1[3]}]
set_property PACKAGE_PIN W18 [get_ports {rd1[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd1[4]}]
set_property PACKAGE_PIN U15 [get_ports {rd1[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd1[5]}]
set_property PACKAGE_PIN U14 [get_ports {rd1[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd1[6]}]
set_property PACKAGE_PIN V14 [get_ports {rd1[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd1[7]}]
set_property PACKAGE_PIN V13 [get_ports {rd2[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd2[0]}]
set_property PACKAGE_PIN V3 [get_ports {rd2[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd2[1]}]
set_property PACKAGE_PIN W3 [get_ports {rd2[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd2[2]}]
set_property PACKAGE_PIN U3 [get_ports {rd2[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd2[3]}]
set_property PACKAGE_PIN P3 [get_ports {rd2[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd2[4]}]
set_property PACKAGE_PIN N3 [get_ports {rd2[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd2[5]}]
set_property PACKAGE_PIN P1 [get_ports {rd2[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd2[6]}]
set_property PACKAGE_PIN L1 [get_ports {rd2[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rd2[7]}]
	


set_property PACKAGE_PIN U18 [get_ports clk]						
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports reset]						
	set_property IOSTANDARD LVCMOS33 [get_ports reset]

